##
## Build
##
FROM golang:1.16-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . ./

RUN go build -o /chat

##
## Deploy
##
FROM gcr.io/distroless/base-debian10

WORKDIR /chat

COPY --from=build /chat /chat
COPY --from=build /app/templates /chat/templates

EXPOSE 8080

ENTRYPOINT ["./chat"]